site_name: Smithproxy Docs
nav:
        - Home: index.md
        - Scenarios: scenarios.md
        - Installation:
            - Run in docker: installing-docker.md 
            - Install from sources: installing-sources.md
        - Post-install:
            - First Setup: post-install.md
        - Signing CA:
            - CA ops: ca-ops.md
        - Traffic captures:
            - Capturing traffic: capture-traffic.md
        - Components: design.md

theme: readthedocs
